# Generated by Django 3.1 on 2020-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0005_auto_20200907_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('institution_id', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('board', models.BooleanField()),
                ('member', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('institution_id', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('governance', models.BooleanField()),
                ('team', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('affiliation', models.CharField(max_length=80)),
                ('bio', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
