# Generated by Django 3.1 on 2020-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_usercommunity_userinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=80)),
                ('affiliation', models.CharField(max_length=80)),
                ('bio', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
