# Generated by Django 3.1 on 2020-09-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_userprofile_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
