# Generated by Django 3.0.7 on 2020-09-29 19:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_researcher', models.BooleanField(default=False)),
                ('orchid', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('nationality', models.CharField(max_length=60, verbose_name='nationality')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city_or_town', models.CharField(max_length=80, verbose_name='city or town')),
                ('job_title', models.CharField(max_length=80, verbose_name='last name')),
                ('community_member', models.BooleanField(default=False)),
                ('affiliation', models.CharField(max_length=60, verbose_name='affiliation')),
                ('bio', models.CharField(max_length=120, verbose_name='bio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=80)),
                ('community_code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=80)),
                ('institution_code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
