# Generated by Django 3.1 on 2020-09-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.CharField(max_length=20)),
                ('community_id', models.CharField(max_length=50)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('board', models.BooleanField()),
                ('member', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Community',
                'verbose_name_plural': 'User Communities',
            },
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.CharField(max_length=20)),
                ('institution_id', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('governance', models.BooleanField()),
                ('team', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Institution',
                'verbose_name_plural': 'User Institutions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=80)),
                ('researcher', models.BooleanField()),
                ('community_member', models.BooleanField()),
                ('affiliation', models.CharField(max_length=80)),
                ('bio', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
