# Generated by Django 3.0.7 on 2020-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200929_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunity',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
