# Generated by Django 3.0.7 on 2020-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercommunity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'approver'), (3, 'writer'), (4, 'editor'), (5, 'implementor')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
    ]
