# Generated by Django 3.0.7 on 2020-10-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200930_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='orchid',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Institution',
                'verbose_name_plural': 'User Institutions',
            },
        ),
    ]
