# Generated by Django 3.0.7 on 2020-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userinstitution_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='orchid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='usercommunity',
            name='roles',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='userinstitution',
            name='roles',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
    ]
