# Generated by Django 3.0.7 on 2020-10-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201001_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.TextField()),
                ('when', models.TextField()),
                ('where', models.TextField()),
                ('what', models.TextField()),
                ('abstract', models.TextField()),
                ('target_species', models.TextField()),
            ],
        ),
    ]
