# Generated by Django 3.0.7 on 2021-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tklabel',
            name='label_type',
            field=models.CharField(choices=[('attribution', 'attribution'), ('clan', 'clan'), ('family', 'family'), ('outreach', 'outreach'), ('tk_multiple_community', 'tk_multiple_community'), ('non_verified', 'non_verified'), ('verified', 'verified'), ('non_commercial', 'non_commercial'), ('commercial', 'commercial'), ('culturally_sensitive', 'culturally_sensitive'), ('community_voice', 'community_voice'), ('community_use_only', 'community_use_only'), ('seasonal', 'seasonal'), ('women_general', 'women_general'), ('men_general', 'men_general'), ('men_restricted', 'men_restricted'), ('women_restricted', 'women_restricted'), ('secret_sacred', 'secret_sacred')], max_length=50, null=True),
        ),
    ]
