# Generated by Django 3.0.7 on 2021-04-14 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0003_auto_20210329_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tklabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='tknotice',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
