# Generated by Django 3.0.7 on 2021-04-14 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0004_auto_20210414_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tklabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tknotice',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
