# Generated by Django 3.0.7 on 2021-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0027_auto_20210420_2235'),
        ('tklabels', '0007_auto_20210414_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='tknotice',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='tknotice_statuses', to='bclabels.NoticeStatus'),
        ),
    ]
