# Generated by Django 3.0.7 on 2021-04-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0008_tknotice_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tklabel',
            name='tk_notice',
        ),
    ]
