# Generated by Django 3.0.7 on 2021-06-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0010_auto_20210505_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tknotice',
            name='message',
        ),
    ]
