# Generated by Django 3.0.7 on 2021-06-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0011_remove_tknotice_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tknotice',
            name='statuses',
        ),
    ]
