# Generated by Django 3.0.7 on 2021-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0013_auto_20210624_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tknotice',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
