# Generated by Django 3.0.7 on 2021-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0015_tklabel_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tknotice',
            name='default_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
