# Generated by Django 3.1.13 on 2022-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0021_delete_tknotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tklabel',
            name='audiofile',
            field=models.FileField(blank=True, upload_to='communities/bclabels/audio'),
        ),
    ]
