# Generated by Django 3.1.13 on 2022-05-12 20:23

from django.db import migrations, models
import tklabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0024_auto_20220405_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tklabel',
            name='audiofile',
            field=models.FileField(blank=True, upload_to=tklabels.models.tklabel_audio_path),
        ),
    ]
