# Generated by Django 3.1.13 on 2022-09-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0045_auto_20220909_2320'),
        ('tklabels', '0030_auto_20220909_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tklabel',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tklabel_community', to='communities.community'),
        ),
    ]
