# Generated by Django 3.1.13 on 2023-07-05 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tklabels', '0031_auto_20220914_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tklabel',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tklabel_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
