# Generated by Django 3.0.7 on 2021-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='what',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='when',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='where',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='who',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='project',
            new_name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
