# Generated by Django 3.0.7 on 2021-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20210114_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='abstract',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
