# Generated by Django 3.0.7 on 2020-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20201105_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_species',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='what',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='when',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='where',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='who',
            field=models.TextField(blank=True, null=True),
        ),
    ]
