# Generated by Django 3.0.7 on 2021-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0003_auto_20210114_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
