# Generated by Django 3.0.7 on 2021-01-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0015_auto_20210118_2332'),
        ('researchers', '0005_project_bclabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bclabels',
            field=models.ManyToManyField(blank=True, related_name='project_labels', to='bclabels.BCLabel', verbose_name='BC Labels'),
        ),
    ]
