# Generated by Django 3.0.7 on 2021-01-27 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchers', '0007_auto_20210127_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),

        migrations.AddField(
            model_name='researcher',
            name='website',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
