# Generated by Django 3.0.7 on 2021-01-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0009_auto_20210127_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date_added',)},
        ),
    ]
