# Generated by Django 3.0.7 on 2021-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0010_auto_20210128_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='principal_investigator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='principal_investigator_affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
