# Generated by Django 3.0.7 on 2021-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0013_auto_20210201_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='orcid',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
