# Generated by Django 3.0.7 on 2021-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0014_auto_20210205_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Item', 'Item'), ('Collection', 'Collection'), ('Expedition', 'Expedition'), ('Publication', 'Publication')], max_length=20, null=True),
        ),
    ]
