# Generated by Django 3.0.7 on 2021-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0016_auto_20210224_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/researcher-images'),
        ),
    ]
