# Generated by Django 3.0.7 on 2021-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0017_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='orcid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
