# Generated by Django 3.0.7 on 2021-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0019_researcher_associated_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
