# Generated by Django 3.0.7 on 2021-06-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0024_auto_20210615_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='location',
        ),
    ]
