# Generated by Django 3.0.7 on 2021-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0025_remove_researcher_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='orcid_auth_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
