# Generated by Django 3.1.13 on 2022-02-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0029_auto_20211001_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='date_connected',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
