# Generated by Django 3.1.13 on 2022-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0030_researcher_date_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='contact_email_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
