# Generated by Django 3.1.13 on 2022-06-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0031_researcher_contact_email_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='projects',
        ),
    ]
