# Generated by Django 3.1.13 on 2022-09-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0033_auto_20220909_2318'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='researcher',
            name='researchers_user_id_ea74ad_idx',
        ),
        migrations.AddIndex(
            model_name='researcher',
            index=models.Index(fields=['id', 'user', 'image'], name='researchers_id_2880ce_idx'),
        ),
    ]
