# Generated by Django 3.0.7 on 2020-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_publicly_listed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
