# Generated by Django 3.0.7 on 2020-12-01 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20201201_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='creator',
        ),
        migrations.AddField(
            model_name='community',
            name='community_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
