# Generated by Django 3.0.7 on 2020-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20201201_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymembers',
            options={'verbose_name': 'Community Members', 'verbose_name_plural': 'Community Members'},
        ),
        migrations.AlterField(
            model_name='communitymembers',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community'),
        ),
    ]
