# Generated by Django 3.0.7 on 2020-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_communityjoinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityjoinrequest',
            options={'verbose_name': 'Member Join Request', 'verbose_name_plural': 'Member Join Requests'},
        ),
        migrations.AlterModelOptions(
            name='invitemember',
            options={'verbose_name': 'Member Invitation', 'verbose_name_plural': 'Member Invitations'},
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
            preserve_default=False,
        ),
    ]
