# Generated by Django 3.0.7 on 2020-12-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20201218_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityjoinrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
        migrations.AlterField(
            model_name='invitemember',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
    ]
