# Generated by Django 3.0.7 on 2020-12-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityMembers',
        ),
    ]
