# Generated by Django 3.0.7 on 2021-01-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_auto_20201222_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
