# Generated by Django 3.0.7 on 2020-12-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_auto_20201203_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunity',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='user_communities', to='communities.Community'),
        ),
    ]
