# Generated by Django 3.0.7 on 2021-01-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_delete_usercommunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityjoinrequest',
            options={'verbose_name': 'Community Join Request', 'verbose_name_plural': 'Community Join Requests'},
        ),
    ]
