# Generated by Django 3.0.7 on 2021-01-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20210120_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityjoinrequest',
            options={'ordering': ('-date_sent',), 'verbose_name': 'Community Join Request', 'verbose_name_plural': 'Community Join Requests'},
        ),
        migrations.AlterModelOptions(
            name='invitemember',
            options={'ordering': ('-created',), 'verbose_name': 'Member Invitation', 'verbose_name_plural': 'Member Invitations'},
        ),
    ]
