# Generated by Django 3.0.7 on 2021-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_auto_20210128_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
