# Generated by Django 3.0.7 on 2021-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_community_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/community-images'),
        ),
    ]
