# Generated by Django 3.0.7 on 2021-05-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_auto_20210510_2022'),
        ('communities', '0019_auto_20210505_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_invitation', to='institutions.Institution'),
        ),
        migrations.AlterField(
            model_name='invitemember',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_invitation', to='communities.Community'),
        ),
    ]
