# Generated by Django 3.0.7 on 2021-05-11 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0020_auto_20210511_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemember',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitemember',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
    ]
