# Generated by Django 3.0.7 on 2021-05-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_auto_20210510_2022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0021_auto_20210511_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8)),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request_community', to='communities.Community')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request_institution', to='institutions.Institution')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Join Request',
                'verbose_name_plural': 'Community Join Requests',
                'ordering': ('-date_sent',),
            },
        ),
        migrations.DeleteModel(
            name='CommunityJoinRequest',
        ),
    ]
