# Generated by Django 3.0.7 on 2021-05-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0022_auto_20210512_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ('-date_sent',), 'verbose_name': 'Join Request', 'verbose_name_plural': 'Join Requests'},
        ),
    ]
