# Generated by Django 3.0.7 on 2021-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210608_2010'),
        ('communities', '0023_auto_20210512_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='community_projects', to='projects.Project'),
        ),
    ]
