# Generated by Django 3.0.7 on 2021-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0024_community_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
