# Generated by Django 3.0.7 on 2021-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0029_joinrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], max_length=8, null=True),
        ),
    ]
