# Generated by Django 3.0.7 on 2021-06-24 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0031_community_support_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_publicly_listed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
