# Generated by Django 3.0.7 on 2021-06-25 20:30

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0032_auto_20210624_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='support_document',
            field=models.FileField(blank=True, null=True, upload_to=communities.models.get_file_path),
        ),
    ]
