# Generated by Django 3.0.7 on 2021-08-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0033_auto_20210625_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='city_or_town',
            new_name='city_town',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='state_or_province',
            new_name='state_province_region',
        ),
    ]
