# Generated by Django 3.0.7 on 2021-08-25 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0049_auto_20210825_1822'),
        ('communities', '0035_community_community_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='editors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='projects',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='community_projects', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='community',
            name='viewers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
