# Generated by Django 3.0.7 on 2021-10-01 19:16

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0036_auto_20210825_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=communities.models.community_img_path),
        ),
    ]
