# Generated by Django 3.0.7 on 2021-10-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0037_auto_20211001_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='is_publicly_listed',
        ),
    ]
