# Generated by Django 3.1.13 on 2022-06-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0040_community_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='projects',
        ),
    ]
