# Generated by Django 3.1.13 on 2022-06-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0041_remove_community_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
