# Generated by Django 3.1.13 on 2022-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0042_auto_20220608_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='native_land_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
