# Generated by Django 3.0.7 on 2020-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201001_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstitution',
            name='institution',
            field=models.ManyToManyField(to='accounts.Institution'),
        ),
    ]
