# Generated by Django 3.0.7 on 2020-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='affiliation',
            field=models.CharField(blank=True, max_length=60, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city_or_town',
            field=models.CharField(blank=True, max_length=80, verbose_name='city or town'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='job_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, max_length=60, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
    ]
