# Generated by Django 3.0.7 on 2020-10-21 21:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
