# Generated by Django 3.0.7 on 2021-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0002_auto_20210317_1602'),
        ('projects', '0005_auto_20210312_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tklabels',
            field=models.ManyToManyField(blank=True, related_name='project_tklabels', to='tklabels.TKLabel', verbose_name='BC Labels'),
        ),
    ]
