# Generated by Django 3.0.7 on 2021-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_tklabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Item', 'Item'), ('Collection', 'Collection'), ('Expedition', 'Expedition'), ('Publication', 'Publication'), ('Sample', 'Sample')], max_length=20, null=True),
        ),
    ]
