# Generated by Django 3.0.7 on 2021-05-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210505_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
