# Generated by Django 3.0.7 on 2021-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recommended_citation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
