# Generated by Django 3.0.7 on 2021-05-19 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210518_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
