# Generated by Django 3.0.7 on 2021-05-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_unique_id'),
    ]

    operations = [
    ]
