# Generated by Django 3.0.7 on 2021-05-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_modified',
            new_name='updated',
        ),
    ]
