# Generated by Django 3.0.7 on 2021-05-19 18:24

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for row in Project.objects.all():
        row.unique_id = uuid.uuid4()
        row.save(update_fields=['unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210519_1821'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
