# Generated by Django 3.0.7 on 2021-06-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20210520_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributors',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contributors', to='projects.Project'),
        ),
    ]
