# Generated by Django 3.0.7 on 2021-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0021_researcher_projects'),
        ('institutions', '0012_institution_projects'),
        ('communities', '0024_community_projects'),
        ('projects', '0023_auto_20210608_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontributors',
            name='community',
        ),
        migrations.RemoveField(
            model_name='projectcontributors',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='projectcontributors',
            name='researcher',
        ),
        migrations.AddField(
            model_name='projectcontributors',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='contributing_communities', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='projectcontributors',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='contributing_institutions', to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='projectcontributors',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='contributing_researchers', to='researchers.Researcher'),
        ),
    ]
