# Generated by Django 3.0.7 on 2021-06-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectperson',
            options={'verbose_name': 'Project Person', 'verbose_name_plural': 'Project People'},
        ),
    ]
