# Generated by Django 3.0.7 on 2021-06-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20210611_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectperson',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectperson',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
