# Generated by Django 3.0.7 on 2021-06-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210611_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectperson',
            options={'verbose_name': 'Additional Contributor', 'verbose_name_plural': 'Additional Contributors'},
        ),
        migrations.AlterField(
            model_name='projectperson',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_contributors', to='projects.Project'),
        ),
    ]
