# Generated by Django 3.0.7 on 2021-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210727_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_discoverable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
