# Generated by Django 3.0.7 on 2021-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210825_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bc_labels',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tk_labels',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
