# Generated by Django 3.0.7 on 2021-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0018_delete_tknotice'),
        ('bclabels', '0037_delete_bcnotice'),
        ('projects', '0046_auto_20210825_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bc_labels',
            field=models.ManyToManyField(blank=True, related_name='project_bclabels', to='bclabels.BCLabel', verbose_name='BC Labels'),
        ),
        migrations.AddField(
            model_name='project',
            name='tk_labels',
            field=models.ManyToManyField(blank=True, related_name='project_tklabels', to='tklabels.TKLabel', verbose_name='TK Labels'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
