# Generated by Django 3.0.7 on 2021-08-25 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0018_delete_tknotice'),
        ('bclabels', '0037_delete_bcnotice'),
        ('projects', '0049_auto_20210825_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bc_labels',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='project_bclabels', to='bclabels.BCLabel', verbose_name='BC Labels'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Discoverable', 'Discoverable'), ('Public', 'Public')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tk_labels',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='project_tklabels', to='tklabels.TKLabel', verbose_name='TK Labels'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
