# Generated by Django 3.0.7 on 2021-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210830_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Item', 'Item'), ('Collection', 'Collection'), ('Sample', 'Sample'), ('Expedition', 'Expedition'), ('Publication', 'Publication'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
