# Generated by Django 3.0.7 on 2021-09-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20210910_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
