# Generated by Django 3.0.7 on 2021-09-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20210928_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
