# Generated by Django 3.0.7 on 2021-10-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20210930_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
