# Generated by Django 3.0.7 on 2021-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20211001_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
