# Generated by Django 3.0.7 on 2021-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20211001_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Discoverable', 'Discoverable'), ('Private', 'Private'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
