# Generated by Django 3.1.13 on 2021-10-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20211015_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
