# Generated by Django 3.1.13 on 2021-12-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20211208_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Discoverable', 'Discoverable'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
