# Generated by Django 3.1.13 on 2022-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20211216_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Discoverable', 'Discoverable'), ('Public', 'Public'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
