# Generated by Django 3.1.13 on 2022-02-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_auto_20220219_0000'),
        ('projects', '0091_auto_20220221_2212'),
    ]

    operations = [
    ]
