# Generated by Django 3.1.13 on 2022-03-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_auto_20220224_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='providers_project_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Discoverable', 'Discoverable'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
