# Generated by Django 3.1.13 on 2022-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_auto_20220304_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_boundary_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Discoverable', 'Discoverable'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
