# Generated by Django 3.1.13 on 2022-03-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_auto_20220317_1914'),
        ('projects', '0099_auto_20220315_1937'),
    ]

    operations = [
    ]
