# Generated by Django 3.1.13 on 2022-06-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0031_researcher_contact_email_public'),
        ('communities', '0040_community_created'),
        ('institutions', '0025_institution_created'),
        ('projects', '0110_auto_20220512_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Discoverable', 'Discoverable'), ('Private', 'Private'), ('Public', 'Public')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_created_project', to='communities.community')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_created_project', to='institutions.institution')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator_project', to='projects.project')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_created_project', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Project Creator',
                'verbose_name_plural': 'Project Creator',
            },
        ),
    ]
