# Generated by Django 3.1.13 on 2022-06-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_auto_20220614_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
