# Generated by Django 3.1.13 on 2022-07-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0120_auto_20220706_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
