# Generated by Django 3.1.13 on 2022-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0137_auto_20220831_2222'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['unique_id', 'project_creator'], name='projects_pr_unique__de7507_idx'),
        ),
    ]
