# Generated by Django 3.1.13 on 2022-09-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0138_auto_20220909_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Discoverable', 'Discoverable'), ('Private', 'Private'), ('Public', 'Public')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='projectcontributors',
            index=models.Index(fields=['project'], name='projects_pr_project_370c72_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcreator',
            index=models.Index(fields=['project'], name='projects_pr_project_358e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project'], name='projects_pr_project_b8d751_idx'),
        ),
        migrations.AddIndex(
            model_name='projectperson',
            index=models.Index(fields=['project'], name='projects_pr_project_64bbea_idx'),
        ),
    ]
