# Generated by Django 3.1.13 on 2022-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0139_auto_20220909_2306'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectcreator',
            name='projects_pr_project_358e5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectnote',
            name='projects_pr_project_b8d751_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Discoverable', 'Discoverable'), ('Private', 'Private')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='projectcreator',
            index=models.Index(fields=['project', 'community', 'institution', 'researcher'], name='projects_pr_project_28b696_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', 'community'], name='projects_pr_project_17f1b6_idx'),
        ),
    ]
