# Generated by Django 3.1.13 on 2022-09-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0140_auto_20220909_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
