# Generated by Django 3.1.13 on 2022-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0144_auto_20220928_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geome_project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publication_date_ongoing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='recommended_citation',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
    ]
