# Generated by Django 3.1.13 on 2022-12-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0150_auto_20221207_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image5',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Discoverable', 'Discoverable'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
