# Generated by Django 3.1.13 on 2022-12-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0151_auto_20221216_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontributors',
            options={'verbose_name_plural': 'Project Contributors'},
        ),
        migrations.AlterModelOptions(
            name='projectcreator',
            options={'verbose_name_plural': 'Project Creator'},
        ),
        migrations.AlterModelOptions(
            name='projectnote',
            options={'verbose_name_plural': 'Project Notes'},
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Discoverable', 'Discoverable')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_activity', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Activity',
            },
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project'], name='projects_pr_project_d69341_idx'),
        ),
    ]
