# Generated by Django 3.1.13 on 2023-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0156_auto_20230131_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_project_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Contributor', 'Contributor'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
