# Generated by Django 3.1.13 on 2023-04-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0160_auto_20230411_1701'),
        ('projects', '0160_auto_20230411_2154'),
    ]

    operations = [
    ]
