# Generated by Django 3.1.13 on 2023-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0161_merge_20230413_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Contributor', 'Contributor'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
