# Generated by Django 3.1.13 on 2023-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0165_auto_20230608_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Contributor', 'Contributor')], max_length=20, null=True),
        ),
    ]
