# Generated by Django 3.0.7 on 2020-12-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcdefaultlabel',
            options={'verbose_name': 'BC Label', 'verbose_name_plural': 'BC Labels'},
        ),
        migrations.AddField(
            model_name='bcdefaultlabel',
            name='modified_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
