# Generated by Django 3.0.7 on 2020-12-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0002_auto_20201228_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BCDefaultLabel',
        ),
    ]
