# Generated by Django 3.0.7 on 2020-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0004_bclabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
