# Generated by Django 3.0.7 on 2020-12-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0006_auto_20201228_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='default_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
