# Generated by Django 3.0.7 on 2020-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0007_auto_20201228_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bclabel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
