# Generated by Django 3.0.7 on 2021-01-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0009_bcnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcnotice',
            name='message',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
