# Generated by Django 3.0.7 on 2021-01-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0010_auto_20210118_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bclabels.BCNotice'),
        ),
    ]
