# Generated by Django 3.0.7 on 2021-01-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0011_bclabel_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bclabel',
            name='label',
        ),
        migrations.AddField(
            model_name='bclabel',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bclabels.BCNotice'),
        ),
    ]
