# Generated by Django 3.0.7 on 2021-01-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0012_auto_20210118_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bclabel',
            old_name='notice',
            new_name='bc_notice',
        ),
    ]
