# Generated by Django 3.0.7 on 2021-01-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0006_auto_20210126_2315'),
        ('institutions', '0004_delete_userinstitution'),
        ('bclabels', '0015_auto_20210118_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcnotice',
            name='placed_by_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AlterField(
            model_name='bcnotice',
            name='placed_by_researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchers.Researcher'),
        ),
    ]
