# Generated by Django 3.0.7 on 2021-01-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0016_auto_20210127_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bclabel',
            options={'ordering': ('-created',), 'verbose_name': 'BC Label', 'verbose_name_plural': 'BC Labels'},
        ),
        migrations.AlterModelOptions(
            name='bcnotice',
            options={'ordering': ('-created',), 'verbose_name': 'BC Notice', 'verbose_name_plural': 'BC Notices'},
        ),
    ]
