# Generated by Django 3.0.7 on 2021-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0017_auto_20210128_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='label_type',
            field=models.CharField(choices=[('provenance', 'provenance'), ('commercialization', 'commercialization'), ('collaboration', 'collaboration'), ('consent_verified', 'consent_verified'), ('multiple_community', 'multiple_community'), ('research', 'research')], max_length=20, null=True),
        ),
    ]
