# Generated by Django 3.0.7 on 2021-02-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('bclabels', '0018_auto_20210129_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcnotice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
