# Generated by Django 3.0.7 on 2021-04-14 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0022_auto_20210414_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
