# Generated by Django 3.0.7 on 2021-04-14 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0023_bclabel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bcnotice',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
