# Generated by Django 3.0.7 on 2021-04-14 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0024_auto_20210414_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bcnotice',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
