# Generated by Django 3.0.7 on 2021-04-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_community_website'),
        ('bclabels', '0026_auto_20210414_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('not_pending', 'not_pending')], max_length=20, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_community', to='communities.Community')),
            ],
            options={
                'verbose_name': 'Notice Status',
                'verbose_name_plural': 'Notice Status',
            },
        ),
        migrations.AddField(
            model_name='bcnotice',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='bcnotice_statuses', to='bclabels.NoticeStatus'),
        ),
    ]
