# Generated by Django 3.0.7 on 2021-04-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0027_auto_20210420_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bclabel',
            name='bc_notice',
        ),
    ]
