# Generated by Django 3.0.7 on 2021-06-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20210614_1825'),
        ('bclabels', '0031_auto_20210602_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcnotice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_bcnotice', to='projects.Project'),
        ),
    ]
