# Generated by Django 3.1.13 on 2021-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0037_delete_bcnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
