# Generated by Django 3.1.13 on 2021-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0040_bcnotice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BCNotice',
        ),
    ]
