# Generated by Django 3.1.13 on 2022-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0041_delete_bcnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='audiofile',
            field=models.FileField(blank=True, upload_to='communities/bclabels/audio'),
        ),
    ]
