# Generated by Django 3.1.13 on 2022-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0043_bclabel_svg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='language',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bclabel',
            name='language_tag',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
