# Generated by Django 3.1.13 on 2022-05-12 20:23

import bclabels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0044_auto_20220405_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='audiofile',
            field=models.FileField(blank=True, upload_to=bclabels.models.bclabel_audio_path),
        ),
    ]
