# Generated by Django 3.1.13 on 2022-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0046_auto_20220706_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bclabel',
            name='version',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
