# Generated by Django 3.1.13 on 2022-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0047_bclabel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=150),
        ),
    ]
