# Generated by Django 3.1.13 on 2022-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0048_auto_20220816_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='name',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='label name'),
        ),
    ]
