# Generated by Django 3.0.7 on 2021-07-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tklabels', '0013_auto_20210624_2256'),
        ('bclabels', '0032_auto_20210624_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=150)),
                ('translation', models.TextField(blank=True)),
                ('bclabel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bclabel_translation', to='bclabels.BCLabel')),
                ('tklabel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tklabel_translation', to='tklabels.TKLabel')),
            ],
            options={
                'verbose_name': 'Label Translation',
                'verbose_name_plural': 'Label Translations',
            },
        ),
    ]
