# Generated by Django 3.0.7 on 2021-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltranslation',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
