# Generated by Django 3.0.7 on 2021-07-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0013_auto_20210624_2256'),
        ('bclabels', '0032_auto_20210624_2256'),
        ('helpers', '0002_labeltranslation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltranslation',
            name='bclabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bclabel_translation', to='bclabels.BCLabel'),
        ),
        migrations.AlterField(
            model_name='labeltranslation',
            name='tklabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tklabel_translation', to='tklabels.TKLabel'),
        ),
    ]
