# Generated by Django 3.0.7 on 2021-07-08 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0033_auto_20210625_2030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tklabels', '0013_auto_20210624_2256'),
        ('bclabels', '0032_auto_20210624_2256'),
        ('helpers', '0003_auto_20210707_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('not_pending', 'not_pending')], max_length=20, null=True)),
                ('bcnotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcnotice_status', to='bclabels.BCNotice')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_community', to='communities.Community')),
                ('tknotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tknotice_status', to='tklabels.TKNotice')),
            ],
            options={
                'verbose_name': 'Notice Status',
                'verbose_name_plural': 'Notice Statuses',
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bcnotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcnotice_comment', to='bclabels.BCNotice')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_community', to='communities.Community')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to=settings.AUTH_USER_MODEL)),
                ('tknotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tknotice_comment', to='tklabels.TKNotice')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('created',),
            },
        ),
    ]
