# Generated by Django 3.0.7 on 2021-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('bc', 'biocultural'), ('tk', 'traditional_knowledge')], max_length=50, null=True),
        ),
    ]
