# Generated by Django 3.0.7 on 2021-09-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0036_auto_20210825_1922'),
        ('projects', '0056_auto_20210901_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpers', '0009_auto_20210819_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesNotified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communities', models.ManyToManyField(blank=True, db_index=True, related_name='communities_notified', to='communities.Community')),
                ('institutions', models.ManyToManyField(blank=True, db_index=True, related_name='institutions_notified', to='communities.Community')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_notified', to='projects.Project')),
                ('researchers', models.ManyToManyField(blank=True, db_index=True, related_name='researchers_notified', to='communities.Community')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_community', to='communities.Community')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_comment', to='projects.Project')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice Comment',
                'verbose_name_plural': 'Notice Comments',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('not_pending', 'not_pending')], max_length=20, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_community', to='communities.Community')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Notice Status',
                'verbose_name_plural': 'Notice Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='noticestatus',
            name='community',
        ),
        migrations.RemoveField(
            model_name='noticestatus',
            name='notice',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='default_text',
            new_name='bc_default_text',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='img_url',
            new_name='bc_img_url',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='communities',
        ),
        migrations.AddField(
            model_name='notice',
            name='tk_default_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='tk_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('biocultural', 'biocultural'), ('traditional_knowledge', 'traditional_knowledge'), ('biocultural_and_traditional_knowledge', 'biocultural_and_traditional_knowledge')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='NoticeComment',
        ),
        migrations.DeleteModel(
            name='NoticeStatus',
        ),
    ]
