# Generated by Django 3.0.7 on 2021-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_auto_20210824_1240'),
        ('researchers', '0026_researcher_orcid_auth_token'),
        ('helpers', '0010_auto_20210901_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitiesnotified',
            options={'verbose_name': 'Entities Notified', 'verbose_name_plural': 'Entities Notified'},
        ),
        migrations.AlterField(
            model_name='entitiesnotified',
            name='institutions',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='institutions_notified', to='institutions.Institution'),
        ),
        migrations.AlterField(
            model_name='entitiesnotified',
            name='researchers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='researchers_notified', to='researchers.Researcher'),
        ),
    ]
