# Generated by Django 3.0.7 on 2021-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0011_auto_20210901_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
