# Generated by Django 3.1.13 on 2021-11-01 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tklabels', '0021_delete_tknotice'),
        ('bclabels', '0041_delete_bcnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpers', '0013_auto_20210910_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('bclabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bclabel_note', to='bclabels.bclabel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_sender', to=settings.AUTH_USER_MODEL)),
                ('tklabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tklabel_note', to='tklabels.tklabel')),
            ],
            options={
                'verbose_name': 'Label Note',
                'verbose_name_plural': 'Label Notes',
            },
        ),
    ]
