# Generated by Django 3.1.13 on 2021-12-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0016_institutionnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionnotice',
            old_name='open_to_collaboration_default_text',
            new_name='open_to_collaborate_default_text',
        ),
        migrations.RenameField(
            model_name='institutionnotice',
            old_name='open_to_collaboration_img_url',
            new_name='open_to_collaborate_img_url',
        ),
        migrations.AlterField(
            model_name='institutionnotice',
            name='notice_type',
            field=models.CharField(choices=[('open_to_collaborate', 'open_to_collaborate'), ('attribution_incomplete', 'attribution_incomplete'), ('open_to_collaborate_and_attribution_incomplete', 'open_to_collaborate_and_attribution_incomplete')], max_length=50, null=True),
        ),
    ]
