# Generated by Django 3.1.13 on 2022-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0017_auto_20211202_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionnotice',
            name='attribution_incomplete_svg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionnotice',
            name='open_to_collaborate_svg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='bc_svg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='tk_svg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
