# Generated by Django 3.1.13 on 2022-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0018_auto_20220224_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltranslation',
            name='language_tag',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
