# Generated by Django 3.1.13 on 2022-05-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0019_labeltranslation_language_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionnotice',
            name='open_to_collaborate_default_text',
        ),
        migrations.RemoveField(
            model_name='institutionnotice',
            name='open_to_collaborate_img_url',
        ),
        migrations.RemoveField(
            model_name='institutionnotice',
            name='open_to_collaborate_svg_url',
        ),
        migrations.AlterField(
            model_name='institutionnotice',
            name='notice_type',
            field=models.CharField(choices=[('attribution_incomplete', 'attribution_incomplete')], max_length=50, null=True),
        ),
    ]
