# Generated by Django 3.1.13 on 2022-07-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0023_opentocollaboratenoticeurl_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='placed_by_institution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='placed_by_researcher',
            new_name='researcher',
        ),
    ]
