# Generated by Django 3.1.13 on 2022-07-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0024_auto_20220706_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltranslation',
            old_name='title',
            new_name='translated_name',
        ),
        migrations.RenameField(
            model_name='labeltranslation',
            old_name='translation',
            new_name='translated_text',
        ),
    ]
