# Generated by Django 3.1.13 on 2022-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0026_auto_20220718_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('biocultural', 'biocultural'), ('traditional_knowledge', 'traditional_knowledge'), ('biocultural_and_traditional_knowledge', 'biocultural_and_traditional_knowledge'), ('attribution_incomplete', 'attribution_incomplete')], max_length=50, null=True),
        ),
    ]
