# Generated by Django 3.1.13 on 2022-07-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0028_auto_20220719_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='tk_default_text',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='tk_img_url',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='tk_svg_url',
        ),
        migrations.DeleteModel(
            name='InstitutionNotice',
        ),
    ]
