# Generated by Django 3.1.13 on 2022-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0029_auto_20220719_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('biocultural', 'biocultural'), ('traditional_knowledge', 'traditional_knowledge'), ('attribution_incomplete', 'attribution_incomplete')], max_length=50, null=True),
        ),
    ]
