# Generated by Django 3.1.13 on 2022-07-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0030_auto_20220719_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_name',
            new_name='name',
        ),
    ]
