# Generated by Django 3.1.13 on 2022-07-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tklabels', '0026_auto_20220706_2035'),
        ('bclabels', '0046_auto_20220706_2035'),
        ('helpers', '0031_auto_20220719_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(blank=True)),
                ('version_text', models.TextField(blank=True)),
                ('version_translated_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(null=True)),
                ('bclabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bclabel_version', to='bclabels.bclabel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_creator', to=settings.AUTH_USER_MODEL)),
                ('tklabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tklabel_version', to='tklabels.tklabel')),
            ],
            options={
                'verbose_name': 'Label Version',
                'verbose_name_plural': 'Label Versions',
            },
        ),
    ]
