# Generated by Django 3.1.13 on 2022-07-22 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpers', '0033_remove_labelversion_version_translated_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
