# Generated by Django 3.1.13 on 2022-07-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0034_labelversion_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTranslationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_name', models.CharField(blank=True, max_length=150)),
                ('language_tag', models.CharField(blank=True, max_length=5)),
                ('language', models.CharField(blank=True, max_length=150)),
                ('translated_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(null=True)),
                ('version_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_version_translation', to='helpers.labelversion')),
            ],
            options={
                'verbose_name': 'Label Translation Version',
                'verbose_name_plural': 'Label Translation Versions',
            },
        ),
    ]
