# Generated by Django 3.1.13 on 2022-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0035_labeltranslationversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelversion',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
