# Generated by Django 3.1.13 on 2022-09-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0028_auto_20220909_2320'),
        ('researchers', '0034_auto_20220909_2320'),
        ('communities', '0045_auto_20220909_2320'),
        ('helpers', '0038_auto_20220909_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_connections', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_connections', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='researcher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_connections', to='researchers.researcher'),
        ),
    ]
