# Generated by Django 3.1.13 on 2022-09-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0040_auto_20220928_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
