# Generated by Django 3.1.13 on 2022-10-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0041_delete_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentocollaboratenoticeurl',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Website'),
        ),
        migrations.AlterField(
            model_name='opentocollaboratenoticeurl',
            name='url',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
    ]
