# Generated by Django 3.1.13 on 2022-12-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0035_auto_20221021_2043'),
        ('institutions', '0028_auto_20220909_2320'),
        ('helpers', '0042_auto_20221021_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_institution', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_researcher', to='researchers.researcher'),
        ),
    ]
