# Generated by Django 3.1.13 on 2022-12-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0043_auto_20221207_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='researcher',
        ),
    ]
