# Generated by Django 3.1.13 on 2022-12-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0045_projectcomment_sender_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentocollaboratenoticeurl',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='Link'),
        ),
    ]
