# Generated by Django 3.1.13 on 2023-01-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0047_projectarchived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectArchived',
        ),
    ]
