# Generated by Django 3.1.13 on 2023-05-01 18:58

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0048_delete_projectarchived'),
    ]

    operations = [
        UnaccentExtension()
    ]
