# Generated by Django 3.1.13 on 2023-06-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0030_auto_20230607_2059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchers', '0035_auto_20221021_2043'),
        ('helpers', '0049_auto_20230501_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeDownloadTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_care_notices', models.BooleanField(default=False, null=True)),
                ('open_to_collaborate_notice', models.BooleanField(default=False, null=True)),
                ('date_downloaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchers.researcher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice Download Tracker',
                'verbose_name_plural': 'Notice Download Tracker',
            },
        ),
    ]
