# Generated by Django 3.1.13 on 2023-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0050_noticedownloadtracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticedownloadtracker',
            old_name='collection_care_notices',
            new_name='collections_care_notices',
        ),
    ]
