# Generated by Django 3.1.13 on 2023-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0052_collectionscarenoticepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionscarenoticepolicy',
            options={'verbose_name': 'Collections Care Notice Policy', 'verbose_name_plural': 'Collections Care Notice Policy'},
        ),
        migrations.AlterField(
            model_name='collectionscarenoticepolicy',
            name='policy_document',
            field=models.FileField(blank=True, null=True, upload_to='institutions/support-files/collections-care-policies'),
        ),
        migrations.AlterField(
            model_name='collectionscarenoticepolicy',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Website URL'),
        ),
    ]
