# Generated by Django 3.1.13 on 2023-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0054_auto_20230727_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_user_id', models.IntegerField(blank=True, null=True)),
                ('action_account_type', models.CharField(blank=True, max_length=250, null=True)),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('researcher_id', models.IntegerField(blank=True, null=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('institution_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('New Member Added', 'New Member Added'), ('Sign-Up Invitation', 'Sign-Up Invitation'), ('New User', 'New User'), ('New Researcher', 'New Researcher'), ('New Community', 'New Community'), ('New Institution', 'New Institution'), ('Project Edited', 'Project Edited'), ('Project Created', 'Project Created'), ('Contributor Added', 'Contributor Added'), ('Community Notified', 'Community Notified'), ('Label(s) Applied', 'Label(s) Applied'), ('Disclosure Notice(s) Added', 'Disclosure Notice(s) Added'), ('Engagement Notice Added', 'Engagement Notice Added')], max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Hub Activity',
                'verbose_name_plural': 'Hub Activity',
            },
        ),
        migrations.AlterModelOptions(
            name='noticetranslation',
            options={'verbose_name': 'Notice Translation', 'verbose_name_plural': 'Notice Translations'},
        ),
    ]
