# Generated by Django 3.1.13 on 2023-08-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0056_auto_20230816_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubactivity',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='hubactivity',
            name='recipient_id',
        ),
    ]
