# Generated by Django 3.1.13 on 2023-08-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0057_auto_20230817_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubactivity',
            name='project_link',
        ),
    ]
