# Generated by Django 3.1.13 on 2023-08-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0058_remove_hubactivity_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubactivity',
            name='researcher_id',
        ),
    ]
