# Generated by Django 3.0.7 on 2020-10-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercommunity',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinstitution',
            old_name='account',
            new_name='user',
        ),
    ]
