# Generated by Django 3.0.7 on 2020-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/communities'),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/institutions'),
        ),
    ]
