# Generated by Django 3.0.7 on 2020-11-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='reason',
            field=models.CharField(choices=[('Register a Community Account', 'Register a Community Account'), ('Register an Institution Account', 'Register an Institution Account'), ('Register a Research Account', 'Register a Research Account')], max_length=200, null=True),
        ),
    ]
