# Generated by Django 3.0.7 on 2021-01-14 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_delete_usercommunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0004_delete_userinstitution'),
        ('accounts', '0002_remove_profile_registration_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutions', models.ManyToManyField(blank=True, to='institutions.Institution')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Institution',
                'verbose_name_plural': 'User Institutions',
            },
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communities', models.ManyToManyField(blank=True, related_name='user_communities', to='communities.Community')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Community',
                'verbose_name_plural': 'User Communities',
            },
        ),
    ]
