# Generated by Django 3.0.7 on 2020-11-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201111_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reason',
        ),
    ]
