# Generated by Django 3.0.7 on 2021-01-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercommunity_userinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=120, null=True)),
                ('date_sent', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sign Up Invitation',
                'verbose_name_plural': 'Sign Up Invitations',
            },
        ),
    ]
