# Generated by Django 3.0.7 on 2020-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_registration_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_reason',
            field=models.CharField(choices=[('', ''), ('community', 'Register a Community Account'), ('institution', 'Register an Institution Account'), ('researcher', 'Register a Research Account')], max_length=12, null=True),
        ),
    ]
