# Generated by Django 3.0.7 on 2020-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201104_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-pic-placeholder.png', null=True, upload_to='photos/'),
        ),
    ]
