# Generated by Django 3.0.7 on 2021-01-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20210120_2254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0004_delete_userinstitution'),
        ('accounts', '0005_signupinvitation_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communities', models.ManyToManyField(blank=True, related_name='user_communities', to='communities.Community')),
                ('institutions', models.ManyToManyField(blank=True, related_name='user_institutions', to='institutions.Institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Affiliation',
                'verbose_name_plural': 'User Affiliations',
            },
        ),
        migrations.RemoveField(
            model_name='userinstitution',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='userinstitution',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCommunity',
        ),
        migrations.DeleteModel(
            name='UserInstitution',
        ),
    ]
