# Generated by Django 3.0.7 on 2021-01-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210121_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
    ]
