# Generated by Django 3.0.7 on 2021-06-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210505_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='community_member',
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='languages spoken'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='preferred language'),
        ),
    ]
