# Generated by Django 3.1.13 on 2022-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_onboarding_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='affiliation'),
        ),
    ]
