# Generated by Django 3.1.13 on 2022-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220826_1424'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='useraffiliation',
            index=models.Index(fields=['user'], name='accounts_us_user_id_e114ee_idx'),
        ),
    ]
