# Generated by Django 3.1.13 on 2022-10-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220915_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
