# Generated by Django 3.1 on 2020-09-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_usercommunity_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
