# Generated by Django 3.1 on 2020-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('board', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('affiliation', models.CharField(max_length=80)),
                ('bio', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
