# Generated by Django 3.1 on 2020-08-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200826_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCommunity',
        ),
        migrations.DeleteModel(
            name='UserInstitution',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
