# Generated by Django 3.1 on 2020-09-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_community_institutions_usercommunity_userinstitution_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCommunity',
        ),
        migrations.DeleteModel(
            name='UserInstitution',
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='institutions',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
    ]
