# Generated by Django 3.1 on 2020-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200907_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.CharField(max_length=20)),
                ('institution_id', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('board', models.BooleanField()),
                ('member', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Community',
                'verbose_name_plural': 'User Communities',
            },
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.CharField(max_length=20)),
                ('institution_id', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('governance', models.BooleanField()),
                ('team', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Institution',
                'verbose_name_plural': 'User Institutions',
            },
        ),
    ]
