# Generated by Django 3.0.7 on 2021-01-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20210114_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinstitution',
            old_name='institution',
            new_name='institutions',
        ),
    ]
