# Generated by Django 3.0.7 on 2021-01-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20210114_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInstitution',
        ),
    ]
