# Generated by Django 3.0.7 on 2021-01-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_delete_userinstitution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='town',
            new_name='town_or_city',
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
