# Generated by Django 3.0.7 on 2021-01-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20210127_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='contact_phone',
            new_name='contact_number',
        ),
    ]
