# Generated by Django 3.0.7 on 2021-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0016_auto_20210224_0052'),
        ('institutions', '0006_auto_20210127_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='address',
            new_name='institution_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='institution_code',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='members',
        ),
        migrations.AddField(
            model_name='institution',
            name='orcid',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='institution_members', to='researchers.Researcher'),
        ),
    ]
