# Generated by Django 3.0.7 on 2021-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20210318_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
