# Generated by Django 3.0.7 on 2021-03-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20210323_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
