# Generated by Django 3.0.7 on 2021-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_auto_20210325_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/institution-images'),
        ),
    ]
