# Generated by Django 3.0.7 on 2021-05-10 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0010_auto_20210505_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='researchers',
        ),
        migrations.AddField(
            model_name='institution',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='institution_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='institution_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='institution_viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
