# Generated by Django 3.0.7 on 2021-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210608_2010'),
        ('institutions', '0011_auto_20210510_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='institution_projects', to='projects.Project'),
        ),
    ]
