# Generated by Django 3.0.7 on 2021-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_institution_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_ror',
            field=models.BooleanField(default=True),
        ),
    ]
