# Generated by Django 3.0.7 on 2021-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20210614_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='orcid',
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
