# Generated by Django 3.0.7 on 2021-06-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_institution_state_or_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='town_or_city',
            new_name='city_or_town',
        ),
    ]
