# Generated by Django 3.0.7 on 2021-10-01 19:16

from django.db import migrations, models
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_remove_institution_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=institutions.models.institution_img_path),
        ),
    ]
