# Generated by Django 3.0.7 on 2021-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_institution_support_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
