# Generated by Django 3.1.13 on 2021-10-20 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0023_auto_20211001_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
