# Generated by Django 3.1.13 on 2021-11-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0024_institution_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
