# Generated by Django 3.1.13 on 2022-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0026_remove_institution_projects'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_creator', 'image'], name='institution_institu_168149_idx'),
        ),
    ]
