# Generated by Django 3.1.13 on 2023-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0028_auto_20220909_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
