# Generated by Django 3.0.7 on 2020-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20201218_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'welcome'), ('invitation', 'invitation'), ('request', 'request'), ('approval', 'approval'), ('accept', 'accept'), ('create', 'create')], max_length=10, null=True),
        ),
    ]
