# Generated by Django 3.0.7 on 2020-12-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_usernotification_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('editor', 'editor'), ('viewer', 'viewer')], max_length=8, null=True),
        ),
    ]
