# Generated by Django 3.0.7 on 2021-01-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210121_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='notification_type',
            field=models.CharField(choices=[('Requests', 'requests'), ('Labels', 'labels'), ('Relationships', 'relationships')], max_length=20, null=True),
        ),
    ]
