# Generated by Django 3.0.7 on 2021-01-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20210122_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('Welcome', 'welcome'), ('Invitation', 'invitation'), ('Request', 'request'), ('Approval', 'approval'), ('Accept', 'accept'), ('Create', 'create')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Editor', 'editor'), ('Viewer', 'viewer')], max_length=8, null=True),
        ),
    ]
