# Generated by Django 3.0.7 on 2021-01-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20210122_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynotification',
            options={'ordering': ('-created',), 'verbose_name': 'Community Notification', 'verbose_name_plural': 'Community Notifications'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('-created',), 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
        migrations.AddField(
            model_name='communitynotification',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
