# Generated by Django 3.0.7 on 2021-04-13 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0013_institutionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_noti_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionnotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_noti_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
