# Generated by Django 3.0.7 on 2021-04-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_auto_20210325_2256'),
        ('tklabels', '0007_auto_20210414_2211'),
        ('bclabels', '0026_auto_20210414_2211'),
        ('notifications', '0014_auto_20210413_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('not_pending', 'not_pending')], max_length=20, null=True)),
                ('bcnotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcnotice_status', to='bclabels.BCNotice')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_community', to='communities.Community')),
                ('tknotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tknotice_status', to='tklabels.TKNotice')),
            ],
            options={
                'verbose_name': 'Notice Status',
                'verbose_name_plural': 'Notice Statuses',
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('bcnotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcnotice_comment', to='bclabels.BCNotice')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_community', to='communities.Community')),
                ('tknotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tknotice_comment', to='tklabels.TKNotice')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created',),
            },
        ),
    ]
