# Generated by Django 3.0.7 on 2021-04-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20210420_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticestatus',
            options={'verbose_name': 'Notice Status', 'verbose_name_plural': 'Notice Status'},
        ),
    ]
