# Generated by Django 3.0.7 on 2021-04-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20210420_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeStatus',
        ),
    ]
