# Generated by Django 3.0.7 on 2021-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_delete_noticestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='notification_type',
            field=models.CharField(choices=[('Labels', 'labels'), ('Connections', 'connections'), ('Activity', 'activity'), ('Projects', 'projects')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='communitynotification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
