# Generated by Django 3.0.7 on 2021-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_auto_20210504_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institutionnotification',
            name='notification_type',
            field=models.CharField(choices=[('Activity', 'activity'), ('Labels', 'labels'), ('Connections', 'Connections'), ('Projects', 'projects')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institutionnotification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
