# Generated by Django 3.0.7 on 2021-05-05 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0017_researcher_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0021_auto_20210505_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('Activity', 'activity'), ('Labels', 'labels'), ('Connections', 'connections'), ('Projects', 'projects')], max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='researchers.Researcher')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_noti_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher Notification',
                'verbose_name_plural': 'Researcher Notifications',
                'ordering': ('-created',),
            },
        ),
    ]
