# Generated by Django 3.0.7 on 2021-05-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_researchernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionnotification',
            options={'ordering': ('created',), 'verbose_name': 'Institution Notification', 'verbose_name_plural': 'Institution Notifications'},
        ),
        migrations.AlterModelOptions(
            name='researchernotification',
            options={'ordering': ('created',), 'verbose_name': 'Researcher Notification', 'verbose_name_plural': 'Researcher Notifications'},
        ),
    ]
