# Generated by Django 3.0.7 on 2021-05-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_auto_20210510_2022'),
        ('notifications', '0026_auto_20210511_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
    ]
