# Generated by Django 3.0.7 on 2021-06-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0023_auto_20210512_2136'),
        ('tklabels', '0012_remove_tknotice_statuses'),
        ('bclabels', '0031_auto_20210602_1853'),
        ('notifications', '0027_usernotification_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('not_pending', 'not_pending')], max_length=20, null=True)),
                ('bcnotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcnotice_status', to='bclabels.BCNotice')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_community', to='communities.Community')),
                ('tknotice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tknotice_status', to='tklabels.TKNotice')),
            ],
            options={
                'verbose_name': 'Notice Status',
                'verbose_name_plural': 'Notice Status',
            },
        ),
    ]
