# Generated by Django 3.0.7 on 2021-06-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_noticestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticestatus',
            options={'verbose_name': 'Notice Status', 'verbose_name_plural': 'Notice Statuses'},
        ),
    ]
