# Generated by Django 3.0.7 on 2021-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0029_auto_20210603_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('-viewed',), 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
