# Generated by Django 3.0.7 on 2021-06-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_auto_20210617_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('viewed',), 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
    ]
