# Generated by Django 3.0.7 on 2021-06-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_auto_20210617_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionnotification',
            options={'ordering': ('viewed',), 'verbose_name': 'Action Notification', 'verbose_name_plural': 'Action Notifications'},
        ),
    ]
