# Generated by Django 3.0.7 on 2021-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_auto_20210617_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
