# Generated by Django 3.1.13 on 2022-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_auto_20210708_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnotification',
            name='notification_type',
            field=models.CharField(choices=[('Labels', 'labels'), ('Connections', 'connections'), ('Activity', 'activity'), ('Projects', 'projects'), ('Members', 'members')], max_length=20, null=True),
        ),
    ]
