# Generated by Django 3.1.13 on 2023-06-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_auto_20220429_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('Welcome', 'welcome'), ('Invitation', 'invitation'), ('Request', 'request'), ('Approval', 'approval'), ('Accept', 'accept'), ('Remove', 'remove')], max_length=10, null=True),
        ),
    ]
